spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_url
    username: db_username
    password: db_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
bakong:
  token: insert_token_bakong
  account:
    id: insert_id
merchant:
  name: insert_your_name
  city: PHNOMPENH
  mobile: insert_your_number
